server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nankai_search?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1017BAba   
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.study.entity
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: teachDemoSecretKey123456789abcdefghijklmn
  expire: 86400000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.study: info